### ISSUE TITLE
Not working on a fresh Wordpress 5.x installation

### ISSUE THREAD

**Issue by salcan** [paulschreiber/liveblog#141]
I get an breaking "uncaught e" js error when I do a fresh WP install and no changes aside from adding the plug. 

Reproduce: Install the plugin, add new liveblog. No slack channel added or any customizations made. 

This page will have the loading gif next the user name continuously load and will throw a JS error every few seconds saying "uncaught e" from app.js. 

If you go ahead and publish: The liveblog's page will not load (appears to be some kind of php error) once published.

Any ideas?

**Comment by paulschreiber** [comment]
What version of WordPress are you using? What version of PHP?
What's the backtrace look like? What steps are involved in "add new liveblog"? You've elided a lot.

**Comment by salcan** [comment]
WP Version 5.4.2
PHP 7.3.18 
WP Theme TwentySeventeen

I'm adding a new liveblog via: /wp-admin/post-new.php?post_type=liveblog and then enabling the live blog. Resulting page that breaks is /live-blog/[title-slug]/

Caught js exception in app.js, line 1033 (formatted):

`  e.prototype.error = function(t) {
            if (!this.isStopped) {
                var e = this._parentSubscriber;
                if (this._error)
                    e.syncErrorThrowable ? (this.__tryOrSetError(e, this._error, t),
                    this.unsubscribe()) : (this.__tryOrUnsub(this._error, t),
                    this.unsubscribe());
                else {
                    if (!e.syncErrorThrowable)
                        throw this.unsubscribe(),
                        t;
                    e.syncErrorValue = t,
                    e.syncErrorThrown = !0,
                    this.unsubscribe()
                }
            }
        }`

unformatted error:
 Uncaught Error: ajax error 0
http://site/wp-content/plugins/liveblog-master/assets/app.js?ver=1.9.8 line 1

No PHP errors, as per WP Debug

The page that doesn't load: /live-blog/[title-slug]/ delivers a totally broken page:
HTTP ERROR 406

Hope this is a bit more clear.

**Comment by paulschreiber** [comment]
This is fixed in 1.9.9.

I found two problem:
*  the default CPT `liveblog` conflicted with a query parameter of the same name. I've changed it to `liveblog_post` and made a note in the comments.
* this fails to work if the time zone is `+0`. Setting it to a regular time zone, i.e. `New York` fixes it.
